TF_0 은 공부하다가 아리까리한거 공부하라고

### About reduce_mean 

The functionality of numpy.mean and tensorflow.reduce_mean are the *same*

In [0]:
import numpy as np       #넘파이로 하는거랑 텐서플로로 하는거랑 평균내는게 어떻게 다른지 비교하려고 하는거임
import tensorflow as tf

In [0]:
c = np.array([[3.,4], [5.,6], [6.,7]])
print(c)

[[3. 4.]
 [5. 6.]
 [6. 7.]]


In [0]:
m1 = np.mean(c, axis = 1) # axis가 1이면 가로방향으로 평균내겠구나 알고있기 
print(m1)

[3.5 5.5 6.5]


In [0]:
m2 = tf.reduce_mean(c, 1)  # (c, 1) = (c, axis = 1)   #이것도 텐서플로에서 평균구하는거다. 
with tf.Session() as sess:  #텐서플로는 세션안에서만 실행이됨. 이미지가 백만장 있다고 하면 위에서는 어떻게 처리할지 설명만해주고 세션안에서 비로소 결과가 나옴.
    result = sess.run(m2)
    print(result)

[3.5 5.5 6.5]
